Added app-launcher component and it's configuration
Asya404/story_library pull request #14
Opened 2024-07-03 14:31 UTC by Asya404

- Added story-app-launcher component.
- Implemented props to configure app-launcher content dynamically.

2024-07-04 23:00 UTC, yyx990805 requested changes

2024-07-04 23:00 UTC, yyx990805 commented on components/story-app-launcher.vue
> +                    <a :href="item.link">{{ item.label }}</a>
there should be item.onClick handler
and if it's defined, then:
```js
<div>
<a v-if="item.link">{{item.label}}</a>
<div v-else-if="item.click" v-on="item.click ? {click: item.click} : {}">{{item.label}}</div>
<div v-else>Error</div>
```

```js
appLauncherItems = [
  {label: 'Home screen', onClick: () => location.href='/'},
  {label: 'Contact', href: '/contact'},
]
```

2024-07-05 10:49 UTC, Asya404 commented on components/story-app-launcher.vue
> +                    <a :href="item.link">{{ item.label }}</a>
@yyx990805 here we need to check **if** there is a link, **else if** there is a custom action, **else** to render an error, right?

2024-07-06 11:44 UTC, yyx990805 commented on components/story-app-launcher.vue
> +                    <a :href="item.link">{{ item.label }}</a>
so error was just to indicate that there should be at least `link` or `click` handler
another way of seeing this would be
```js
<a v-if="item.link" :href="item.link">{{item.label}}</a>
<div v-else-if="item.click" @click="event => item.click(event)" role="button">{{item.label}}</div>
```

2024-07-06 13:42 UTC, Asya404 commented on components/story-app-launcher.vue
> +                    <a :href="item.link">{{ item.label }}</a>
@yyx990805 could you check the last commit, where i implemented that

2024-07-06 13:46 UTC, yyx990805 commented on components/story-app-launcher.vue
> +                    <a :href="item.link">{{ item.label }}</a>
it's good now, we can be merging

2024-07-06 13:47 UTC, yyx990805 approved these changes
ok, both `href` and `onClick` (for interactive calls) are handled, we can merge

2024-07-07 10:24 UTC, merged