Added list-builder component and it's configuration
Asya404/story_library pull request #16
Opened 2024-07-04 13:24 UTC by Asya404

- Added story-list-builder component.
- Implemented props to configure list-builder content dynamically.

2024-07-04 22:53 UTC, yyx990805 requested changes

2024-07-04 22:53 UTC, yyx990805 commented on components/story-list-builder.vue
> +                      </td>
those cells should be read from prop like:
`<list-builder :cells='["label", "productCode", "listPrice", "productFamily"]'/>`

2024-07-04 22:53 UTC, yyx990805 commented on app.vue
> +const listBuilderHeadings = ref(["Name", "Product Code", "List Price", "Product Family"]);
headers should be read from a prop value, like:
those cells should be read from prop like:
`<list-builder :data="[{}, {}, {}]" :headers='["Name", "Product Code", "List Price", "Product Family"]'/>`

2024-07-05 11:01 UTC, Asya404 commented on app.vue
> +const listBuilderHeadings = ref(["Name", "Product Code", "List Price", "Product Family"]);
@yyx990805 here i have prop for data (items) and prop for headings. I didn't get what to change here. 

I could add default keys from objects if headings in separate array are not provided as you suggested for data-table PR.

2024-07-07 12:28 UTC, yyx990805 commented on components/story-list-builder.vue
> +                      </td>
so this means that
```diff


+  <td v-for="cells || [
-  <th scope="row">
-    <div class="slds-truncate" title="Analytics">{{ item.label }}</div>
-  </th>
+  {title: 'Analytics', propName: 'label'},
-  <td role="gridcell">
-    <div class="slds-truncate" title="ANTLY">{{ item.productCode }}</div>
-  </td>
+  {title: 'ANTLY', propName: 'productCode'},
-  <td role="gridcell">
-    <div class="slds-truncate" title="5000.00">{{ item.listPrice }}</div>
-  </td>
+  {title: '5000.00', propName: 'listPrice'},
-  <td role="gridcell">
-    <div class="slds-truncate" title="Analytics Product">{{ item.productFamily }}</div>
-  </td>
+  {title: 'Analytics Product', propName: 'productFamily'},
+  ]" role="gridcell">
+  <div class="slds-truncate" :title="cell.title">{{ item[cell.propName] }}</div>
+</td>
```

2024-07-07 16:18 UTC, Asya404 commented
@yyx990805 I think I get it, but managed it another way as in data-table component. The thing was that cells were hardcoded

2024-07-07 16:45 UTC, yyx990805 approved these changes
good job, can be merged

2024-07-07 16:45 UTC, yyx990805 commented on components/story-list-builder.vue
> +const cellKeys = props.headings ? props.headings : Object.keys(props.items[0]);
looks good! exactly what I wanted in this PR (enough and not more than absolute minimum)

_future_ (not this PR): in next pull requests we will handle `:items` with value like
```js
[{a,b,c},{c,d]]
```
so cellKeys will contain `['a','b','c','d']`

2024-07-07 16:45 UTC, yyx990805 commented on app.vue
> +      <story-list-builder v-if="selectedOption === '17'" :items="listBuilderItems" :headings="listBuilderHeadings"
for future: if we have optional props, then it would be the best to have something like checkbox for this specific prop

```html
<label><input v-model="isListBuilderCustomHeadings">custom headings</label>
<story-list-builder :items="[]" :headings="isListBuilderCustomHeadings ? listBuilderHeadings : undefined"/>
```
but for now it's fine, it's better to have not documented optional props then avoiding implementing optional props because you might need to put extra work to document theirs optionalitiy :)

2024-07-07 18:45 UTC, Asya404 commented
@yyx990805 ok, I understand, I could manage it by flatMap and Set. And for checkbox for optional prop also get it :)

2024-07-07 18:51 UTC, merged